create table if not exists provider_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete set null,
  provider text not null,
  route text not null,
  units int not null default 1,
  cost_usd numeric(10, 4) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_provider_usage_created on provider_usage(created_at desc);

alter table provider_usage enable row level security;
