create table if not exists analysis_runs (
  id bigint generated by default as identity primary key,
  as_of timestamptz not null,
  regime_score double precision not null default 0,
  watchlist text[] not null default '{}',
  status text not null default 'running' check (status in ('running','completed','partial','failed')),
  trigger_source text not null default 'manual',
  config_version text not null default 'mvp-v1',
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists signals (
  id bigint generated by default as identity primary key,
  run_id bigint not null references analysis_runs(id) on delete cascade,
  symbol text not null,
  decision text not null check (decision in ('BUY','HOLD','SELL')),
  confidence double precision not null check (confidence between 0 and 1),
  score double precision not null,
  last_price double precision not null,
  reasons text[] not null default '{}',
  ai_explanation text,
  created_at timestamptz not null default now(),
  unique(run_id, symbol)
);

create table if not exists engine_outputs (
  id bigint generated by default as identity primary key,
  run_id bigint not null references analysis_runs(id) on delete cascade,
  ticker text not null,
  market text not null default 'US',
  run_timestamp timestamptz not null,
  engine_name text not null,
  engine_version text not null default 'mvp-v1',
  direction text not null check (direction in ('bullish','neutral','bearish')),
  confidence int not null check (confidence between 0 and 100),
  time_horizon text not null default 'swing',
  thesis_summary text,
  bull_case text[] not null default '{}',
  bear_case text[] not null default '{}',
  risk_flags text[] not null default '{}',
  catalysts text[] not null default '{}',
  suggested_next_action text,
  raw_payload jsonb,
  raw_payload_ref text,
  source_tag text,
  created_at timestamptz not null default now(),
  unique(run_id, engine_name, ticker, time_horizon)
);

create table if not exists consensus_signals (
  id bigint generated by default as identity primary key,
  run_id bigint not null references analysis_runs(id) on delete cascade,
  ticker text not null,
  market text not null default 'US',
  time_horizon text not null default 'swing',
  direction text not null check (direction in ('bullish','neutral','bearish')),
  agreement_score double precision not null check (agreement_score between 0 and 1),
  confidence_score double precision not null check (confidence_score between 0 and 1),
  freshness_score double precision not null check (freshness_score between 0 and 1),
  conflict_flag boolean not null default false,
  engines_total int not null,
  engines_bullish int not null,
  engines_neutral int not null,
  engines_bearish int not null,
  rationale text,
  next_action text,
  created_at timestamptz not null default now(),
  unique(run_id, ticker, time_horizon)
);

create table if not exists daily_briefs (
  id bigint generated by default as identity primary key,
  run_id bigint references analysis_runs(id) on delete cascade,
  brief_date date not null,
  title text not null,
  summary text not null,
  top_conviction jsonb not null default '[]',
  high_conflict jsonb not null default '[]',
  key_catalysts jsonb not null default '[]',
  markdown text,
  created_at timestamptz not null default now(),
  unique(run_id)
);

create table if not exists pipeline_events (
  id bigint generated by default as identity primary key,
  run_id bigint references analysis_runs(id) on delete cascade,
  stage text not null,
  status text not null check (status in ('started','completed','warning','failed')),
  message text,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists idx_analysis_runs_created on analysis_runs(created_at desc);
create index if not exists idx_signals_run_id on signals(run_id);
create index if not exists idx_engine_outputs_run_ticker on engine_outputs(run_id, ticker);
create index if not exists idx_consensus_run_ticker on consensus_signals(run_id, ticker);
create index if not exists idx_daily_briefs_date on daily_briefs(brief_date desc);
create index if not exists idx_pipeline_events_run on pipeline_events(run_id, created_at);

alter table analysis_runs enable row level security;
alter table signals enable row level security;
alter table engine_outputs enable row level security;
alter table consensus_signals enable row level security;
alter table daily_briefs enable row level security;
alter table pipeline_events enable row level security;

-- Server routes use the service role. No anonymous table access is granted.
