alter table public.analysis_runs
  add column if not exists question text,
  add column if not exists intent text;

create table if not exists public.analysis_reports (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.analysis_runs(id) on delete cascade,
  ticker text not null,
  question text not null,
  intent text not null,
  status text not null check (status in ('complete', 'fallback')),
  view text not null check (view in ('favorable', 'mixed', 'unfavorable', 'insufficient_evidence')),
  confidence text not null check (confidence in ('low', 'medium', 'high')),
  report jsonb not null,
  created_at timestamptz not null default now(),
  unique(run_id, ticker)
);

create index if not exists idx_analysis_reports_run on public.analysis_reports(run_id, ticker);
alter table public.analysis_reports enable row level security;
